docs: Implement Herodotos.
wiris/thoth pull request #1
Opened 2021-11-22 14:05 UTC by jgonzalez-at-wiris

He integrado, como he podido, Herodotos. 

Hay muchas cosas por definir, como las politicas de PR, de nombres de directorios, etc. Pero como primer paso me he tomado la licencia de escribir sin preguntar primero. 

Muchos de los ficheros obligatorios los he añadido aún no teniendo mucho sentido, pero bueno creo que el resultado final puede ser suficientemente satisfactorio.

2021-11-22 15:53 UTC, dmas-at-wiris requested changes

2021-11-22 15:53 UTC, dmas-at-wiris commented on README.md
> +- [#engineering](https://wiris.slack.com/archives/C010P3E9AHH)
Alguien tiene que ser responsable de Thoth. No vale decir todo ingeniería.

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/README.md
> +
```suggestion

```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/README.md
> +This project acts as a `plain text file repository`. If you application needs to consume a file content with no logic involved, Thoth can help you.
```suggestion
This project acts as a `plain text file repository`. If your application needs to consume a file content with no logic involved, Thoth can help you.
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/STRUCTURE.md
> +The rest of the folders in this repository are meant to contain any `plain text file`, grouped by certain criteria. Most of the time the criteria to be used is the product that will consume that file
```suggestion
The rest of the directories in this repository are meant to contain any `plain text file`, grouped by certain criterion. Most of the time the criterion to be used is the product that will consume that files, but no rules regarding this topic have been set __for the moment__, so as a rule of thumb, just use the common sense.
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/STRUCTURE.md
> +└── [product_name]      - Folder containing any plan text file to be consumed 'in app'.
```suggestion
└── [product_name]      - Directory containing any plan text file to be consumed 'in app'.
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/STRUCTURE.md
> +## Other folders
```suggestion
## Other directories
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/USAGE.md
> +  1. Create a folder with a significative name in the root directory of the project (if it does not exist yet). No rules regarding naming folder have been set yet, so just use the common sense.
```suggestion
  1. Create a directory with a meaningful name in the root directory of the project (if it does not exist yet). No rules regarding naming directory have been set yet, so just use the common sense.
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/USAGE.md
> +  2. Create as many `plain text files` as needed in that folder. How you name those files is up to you. Again, apply the common sense.
```suggestion
  2. Create as many `plain text files` as needed in that directory. How you name those files is up to you. Again, apply the common sense.
```

2021-11-22 15:53 UTC, dmas-at-wiris commented on docs/USAGE.md
> +Thoth acts as a `plain text repository` hosted by Github. If you application needs to consume a file content with no logic involved, Thoth can help you.
```suggestion
Thoth acts as a `plain text repository` hosted by Github. If your application needs to consume a file content with no logic involved, Thoth can help you.
```

2021-11-22 16:04 UTC, jgonzalez-at-wiris commented on README.md
> +- [#engineering](https://wiris.slack.com/archives/C010P3E9AHH)
@ifenor-at-wiris

2021-11-24 10:21 UTC, ifenor-at-wiris commented on README.md
> +- [#engineering](https://wiris.slack.com/archives/C010P3E9AHH)
El proyecto es mantenido por todo el equipo de ingeniería pero la última palabra sobre lo que allí puede o no ir recae sobre los leads de ingenería. Dado que no podemos caer en el error de usarlo a discreción. Por tanto a la frase que ya existe le añadiría un "para usar thoth en tu producto debes hablar con los leads de ingeniería" a través del canal #engineering

2021-11-24 10:21 UTC, ifenor-at-wiris commented on README.md
> +
Me falta una frase que describa qué es Thoth.

2021-11-24 10:21 UTC, ifenor-at-wiris commented on docs/README.md
> +This project acts as a `plain text file repository`. If your application needs to consume a file content with no logic involved, Thoth can help you.
Esto está bien, pero falta antes una descripción de qué es Thoth y para qué sirve, me refiero a que se usa para guardar archivos que pueden usar nuestros productos para mostrar en ellos un mensaje a nuestros clientes.

2021-11-24 10:21 UTC, ifenor-at-wiris commented on docs/USAGE.md
> +# Using Thoth
En algún lugar de este archivo pondría que dado que Thoth es un un MVP, antes de añadir nuevos productos se debe consultar a los Leads de Ingeniería.
También algún texto y enlace a las limitaciones que da Github a la hora de consumir su "raw content"

2021-11-24 10:21 UTC, ifenor-at-wiris commented on docs/USAGE.md
> +TODO: Define PR policies.
Si la modificación es sobre archivos ya existentes el PR se limita a los miembros del squad, si el cambio es por añadir un nuevo producto, el PR debe englobar a los leads de ingeniería

2021-11-24 10:28 UTC, ifenor-at-wiris commented on docs/USAGE.md
> +TODO: Define PR policies.
La manera de englobar a todos los leads de ingeniería es con @ wiris/engineering-leads (lo he separado de la @ para no generar un aviso a todos con este comentario)

2021-11-24 11:51 UTC, jgonzalez-at-wiris commented on docs/USAGE.md
> +TODO: Define PR policies.
Hecho

2021-11-24 11:51 UTC, jgonzalez-at-wiris commented on docs/USAGE.md
> +# Using Thoth
Hecho

2021-11-24 11:51 UTC, jgonzalez-at-wiris commented on README.md
> +
Añadido en los dos readme.

2021-11-24 11:52 UTC, jgonzalez-at-wiris commented on docs/README.md
> +This project acts as a `plain text file repository`. If your application needs to consume a file content with no logic involved, Thoth can help you.
Hecho

2021-11-25 07:37 UTC, ifenor-at-wiris approved these changes
Una gran documentación @jgonzalez-at-wiris, muchas gracias

2021-11-25 16:20 UTC, merged